version: '3.8'

services:
  jenkins-master:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins-master
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins-net
  jenkins-agent:
    build: .
    container_name: jenkins-builder
    expose:
      - "22"
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${SSH_PUB_KEY}
    networks:
      - jenkins-net

volumes:
  jenkins_home:

networks:
  jenkins-net:
